import hero from "../assets/hero.png"
import heroMobile from "../assets/hero-mobile.png"
import iPhone from "../assets/iPhone.png"
import heroBlueBlur from "../assets/blue-blur.png"
import heroBlueBlurLeft from "../assets/blue-blur-left.png"
import inventoryBlur from "../assets/inventory-blur.png"
import inventoryOne from "../assets/inventory-one.svg"
import inventoryTwo from "../assets/inventory-two.svg"
import inventoryThree from "../assets/inventory-three.svg"
import simplifiedPayment from "../assets/payment-processing.png"
import priceAutomation from "../assets/price-automation.png"
import insights from "../assets/insights.png"
import insightsMobile from "../assets/insights-mobile.png"
import insightsMobileSvg from "../assets/insights-mobile.svg"
import manageOnDevices from "../assets/manage-on-devices.png"
import startSellingOne from "../assets/start-selling-one.svg"
import startSellingTwo from "../assets/start-selling-two.svg"
import startSellingThree from "../assets/start-selling-three.svg"
import startSellingFour from "../assets/start-selling-four.svg"
import integrations from "../assets/integrations.png"
import phones from "../assets/phones.png"
import checkout from "../assets/checkout.png"
import checkoutMobile from "../assets/checkout-mobile.png"
import checkoutMobileSvg from "../assets/checkout-mobile.svg"
import GrowthTool from "../assets/growth-tool.png"
import GrowthToolMobile from "../assets/growth-tool-mobile.png"
import GrowthToolMobileSvg from "../assets/growth-tool-mobile.svg"
import ContactBlur1 from "../assets/Contact-Blur-1.png"
import ContactBlur2 from "../assets/Contact-Blur-2.png"
import step2Popup  from "../assets/step2-popup.png"
import step3Popup  from "../assets/step3-popup.png"
import step4Popup  from "../assets/step4-popup.png"
import setupStep1 from "../assets/setup-store-1.png"
import setupStep4 from "../assets/setup-store-2.png"
import onboardingg from '../assets/onboardingg.png'
import onboardingStep2 from "../assets/onboarding-step-1.png"
import onboardingStep3 from "../assets/onboarding-step-2.png"
import onboardingStep4 from "../assets/onboarding-step-4.png"
import onboardingStep5 from "../assets/onboarding-step-5.png"
import paymentMethod from "../assets/paymentMethod.png"
import manageSales1 from "../assets/manageSales.png"
import manageSales2 from "../assets/manage-sales-1.png"
import manageSales3 from "../assets/manage-sales-2.png"
import manageInventory from "../assets/inventory.png"
import addingProducts1 from "../assets/add-products.png"
import addingProducts2 from "../assets/add-products-1.png"
import addingProducts3 from "../assets/add-products-2.png"
import editingProducts from "../assets/edit-products.png"
import paymentHistory from "../assets/payoutHistory.png"
import customerInfo1 from "../assets/customer-info-1.png"
import customerInfo2 from "../assets/customer-info-2.png"
import customerInfo3 from "../assets/customer-info-3.png"
import offlineSale1 from "../assets/offline-sales-1.png"
import offlineSale2 from "../assets/offline-sales-2.png"
import offlineSale3 from "../assets/offline-sales-3.png"
import offlineSale4 from "../assets/offline-sales-4.png"
import offlineSale5 from "../assets/offline-sales-5.png"
import domain1 from "../assets/domain-1.png"
import domain2 from "../assets/domain-2.png"
import domain3 from "../assets/domain-3.png"
import domain4 from "../assets/domain-4.png"
import domain5 from "../assets/domain-5.png"
import domain6 from "../assets/domain-6.png"
import domain7 from "../assets/domain-7.png"
import domain8 from "../assets/domain-8.png"
import domain9 from "../assets/domain-9.png"
import domain10 from "../assets/domain-10.png"
import delivery1 from "../assets/setup-delivery.png"
import delivery2 from "../assets/setup-delivery-2.png"
import discountedSales1 from "../assets/discounted-sales-1.png"
import discountedSales2 from "../assets/discounted-sales-2.png"
import discountedSales3 from "../assets/discounted-sales-3.png"
import kyc1 from "../assets/kyc-1.png"
import kyc2 from "../assets/kyc-2.png"
import analytics1 from "../assets/business-analytics.png"
import analytics2 from "../assets/business-analytics-2.png"
import analytics3 from "../assets/business-analytics-3.png"
import analytics4 from "../assets/business-analytics-4.png"
import customize1 from "../assets/customize-store.png"
import customize2 from "../assets/customize-store-1.png"
import customize3 from "../assets/customize-store-2.png"
import customize4 from "../assets/customize-store-3.png"
import featuredCatergory from "../assets/featured-category.png"
import discount1 from "../assets/discount-1.png"
import discount2 from "../assets/discount-2.png"
import discount3 from "../assets/discount-3.png"
import freeShipping1 from "../assets/freeshipping1.png"
import freeShipping2 from "../assets/freeshipping2.png"
import wholesale1 from "../assets/wholesale-products-1.png"
import wholesale2 from "../assets/wholesale-products-2.png"
import wholesale3 from "../assets/wholesale-products-3.png"

const images = {
    hero, heroMobile, iPhone, insights, manageOnDevices,
    heroBlueBlur, heroBlueBlurLeft, inventoryBlur, simplifiedPayment, priceAutomation, phones,
    inventoryOne, inventoryTwo, inventoryThree, heroMobile, integrations, delivery1, delivery2, customize1, customize2, customize3, customize4,
    startSellingOne, startSellingTwo, startSellingThree, startSellingFour, customerInfo1, customerInfo2, customerInfo3, discount1, discount2, discount3,
    checkout, checkoutMobile, insightsMobile, insightsMobileSvg, GrowthTool, paymentHistory, offlineSale1, offlineSale2, featuredCatergory, onboardingg,
    offlineSale3, offlineSale4, offlineSale5, domain1, domain2, domain3, domain4, domain5, domain6, domain7, domain8, domain9, domain10, freeShipping1, freeShipping2,
    GrowthToolMobile, GrowthToolMobileSvg, checkoutMobileSvg, ContactBlur1, ContactBlur2, editingProducts, discountedSales1, discountedSales2, discountedSales3,
    step2Popup, step3Popup, step4Popup, manageInventory, addingProducts1, addingProducts2, addingProducts3, kyc1, kyc2, analytics1, analytics2, analytics3, analytics4,
    setupStep1, setupStep4, onboardingStep2, onboardingStep3, onboardingStep4, onboardingStep5, paymentMethod, manageSales1, manageSales2, manageSales3, wholesale1, wholesale2, wholesale3,
};

export default images;